package com.edusync.api.notification.enums;

public enum NotificationType {
    SESSION_SCHEDULED,
    SESSION_STARTING,
    SESSION_RECORDING_READY,
    ASSESSMENT_PUBLISHED,
    ASSESSMENT_GRADED,
    ASSESSMENT_DUE_REMINDER,
    QUIZ_PUBLISHED,
    QUIZ_GRADED,
    MATERIAL_UPLOADED,
    MODULE_PUBLISHED,
    MESSAGE_RECEIVED,
    THREAD_ESCALATED,
    BROADCAST_RECEIVED,
    ENROLLMENT_CONFIRMED,
    CERTIFICATE_ISSUED,
    COURSE_COMPLETED,
    ATTENDANCE_FLAGGED
}
